apiVersion: v1
kind: Service
metadata:
  name: expense-backend
spec:
  selector:
    app: expense-backend
    color: blue   # <-- ACTIVE color (will flip between blue/green)
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
